name: Heroku Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
  
    - name: Release App
      run: | 
        heroku container:release web --app brainb
